### ISSUE TITLE
能否不使用@RestController方式进行消息发送？

### ISSUE THREAD

**Issue by wwjjkk** [ThierrySquirrel/rocketmq-spring-boot-starter#5]
能否或如何通过@Autowired方式触发消息发送，而不要通过http的get方式来调用。
个人尝试时按照文档收发消息没有问题，但必须通过http方式调用吗？

**Comment by ThierrySquirrel** [comment]
可以不通过@RestController方式，需要保证消息被注入，@Autowired是支持的

**Comment by ThierrySquirrel** [comment]
没有其它问题的话，将在24小时内关闭此问题。

**Comment by wwjjkk** [comment]
> 可以不通过@RestController方式，需要保证消息被注入，@Autowired是支持的

如何保证消息被注入呢？我通过@AutoWired方式注入，进行方法调用时会报错
Exception in thread "SendMessage" java.lang.NullPointerException
	at com.github.thierrysquirrel.core.strategy.SendMessageStrategy.send(SendMessageStrategy.java:24)
	at com.github.thierrysquirrel.core.factory.SendMessageFactory.sendMessage(SendMessageFactory.java:29)
	at com.github.thierrysquirrel.core.strategy.ProducerStrategy.statsSendMessage(ProducerStrategy.java:32)
	at com.github.thierrysquirrel.core.factory.execution.SendMessageFactoryExecution.statsSendMessage(SendMessageFactoryExecution.java:40)
	at com.github.thierrysquirrel.thread.AbstractSendMessageThread.run(AbstractSendMessageThread.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by wwjjkk** [comment]
ProducerStrategy第31行Producer producer = ProducerConsumerFactory.getProducer(consumerContainer, rocketMessage, commonMessage); 其中producer返回为null

**Comment by ThierrySquirrel** [comment]
保证消息被注入,确保消息发送者有@RocketMessage注解

**Comment by wwjjkk** [comment]
参考文档Common对象，去掉@RestController和@GetMapping后通过@Autowired引入其他类调用，会爆出上述错误，按理来说消息有被注入吧。大致跟了一下代码，发现PutProducerStrategy的putProducer确实能正确设置producerConsumer，但获取Producer的时候为什么参数是 consumerContainer？ProducerStrategy第31行Producer producer = ProducerConsumerFactory.getProducer(consumerContainer, rocketMessage, commonMessage); 其中producer返回为null

**Comment by ThierrySquirrel** [comment]
您好,经过调查发现,错误为消息初始化未完成,便开始发送消息.
解决方案:消息初始化采用异步无阻塞模式,根据机器配置,及网络情况,初始化所需要时间不同,请耐心等待几秒后,尝试发送消息.

**Comment by wwjjkk** [comment]
主线程sleep几秒后就不报错了.......

**Comment by ThierrySquirrel** [comment]
好的,如果您有其它提问,可在此处继续提出.
如果没有其它提问,此问题将在24小时内关闭.
